create database eaturkish;

create EXTENSION "uuid-ossp";

create table users(
    user_id uuid default uuid_generate_v4(),
    username varchar(30) not null,
    password varchar(12) not null
);

create table subscribers(
    subscriber_id UUID default uuid_generate_v4(),
    subscriber_email text check(subscriber_email ~ '^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$') not null unique
);

create table categories(
    category_id UUID default uuid_generate_v4() primary key,
    category_name text not null unique
);

create table news(
    news_id uuid default uuid_generate_v4(),
    news_img text not null,
    news_title text not null,
    news_desc text not null,
    created_at timestamp default current_timestamp
);

create table messages(
    message_id uuid default uuid_generate_v4(),
    client_name varchar(32) not null,
    client_phone varchar(12) not null,
    client_email text check(client_email ~ '^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$') not null,
    message_body text not null,
    created_at timestamp default current_timestamp
);

create table foods(
    food_id uuid default uuid_generate_v4(),
    food_img text not null,
    food_name varchar(255) not null,
    food_price decimal(9, 2) not null,
    food_stars int default 0,
    count_of_vote int default 0,
    food_category uuid references categories(category_id) not null
);

insert into users (username, password) values('ali', '12345678');

insert into news (news_id, news_img, news_title, news_desc, created_at) values ('3fcd458a-c8ad-4bfa-ad64-e25773e2cf35','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16608241359201news.jpg?alt=media&token=1b5d3ede-e893-4942-8d9c-c4a58e7fdbe4','Reviews of our guests','We were struggling for somewhere to eat around that area. We were hungry and saw that this place was halal and it had good reviews. It looked small but the guy there said there is space for us to sit.\nWe went there it was a warm welcome and the guy told us what to order. The food kept on coming and it was such good value for money. It was good quality food and meat it didn''t feel cheap. The bread is freshly made and the salad was amazing! It was all incredible he even gave us the most amazing Backlava to eat after and also we sat there for ages and they didn''t mind.\nIts always busy and it was just the best surprise! Loved it and I will go back!','2022-08-18T12:02:42.321Z');
insert into news (news_id, news_img, news_title, news_desc, created_at) values ('fa2f68f4-7b95-475c-a9f9-78bb5d50c6ce','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16608242155872news.png?alt=media&token=25f80231-e1ed-40e9-9488-e1b8423d8201','WiFi and environmental issues','The restaurant doesn''t have a WiFi connection and live in 2021\, I had to call my colleagues on google meet\, the stuff said they don''t have an available WiFi. Then I decided to have a meal\, they offered me to get a baklava\, it was very unhealthy food. If they offer you to eat baklava don''t eat\, if you try to deny it they are going to act very rude. I had to call the police because I was scared of them. I can''t believe how they can open restaurant in a first world country\, WAKE UP LONDON!','2022-08-18T12:03:46.934Z');
insert into news (news_id, news_img, news_title, news_desc, created_at) values ('e6450474-6472-4040-95d0-2668826c5ca5','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16608243284373news.jpg?alt=media&token=80b92070-fa2d-4d15-9750-a1ef8d66a4b7','Lier Albanian chief','I am in Eaturkish restaurant now. Its been 25 minutes. Few people came after me and they got their food. I ordered mix doner it shouldnt take more than 10 minutes to make it .It was my first time in here. I am very disappointed with the service. I will never come again. Show less. Date of visit: April 2021','2022-08-18T12:05:33.967Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('a2fe3171-0914-40e6-a409-60af9a9c8d30','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16609138127244news.jpg?alt=media&token=243278da-a381-46bc-9acb-abdd37f9b402','Buffalo Wild Wings: Saucy Chicken Sandwich','On July 18\, Buffalo Wild Wings launched their Saucy Chicken Sandwich\, which coats hand-breaded chicken in any of their 26 signature sauces and seasonings. From Lemon Pepper to Mango Habanero and everything in-between\, customers can make the chicken sandwich their own.','2022-08-19T12:57:00.664Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('15cd3d93-693b-4ea0-b370-2fb2b2da6d8b','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16609143847445news.webp?alt=media&token=cc8e7383-6e5e-412f-b85e-034d00035331','Taco Bell: Flamin'' Hot Cool Ranch Doritos Locos Tacos','It''s the 10th anniversary of the arrival of the first Doritos Locos Tacos at Taco Bell\, and to celebrate\, the chain is introducing its newest flavor to the lineup: the Flamin'' Hot Cool Ranch Doritos Locos Taco — which takes the spicy and cool crunchy shells and uses them as the base for Taco Bell''s beloved tacos. Available on their own for $1.99\, or as a Supreme for $2.49.\n\nThere''s also Doritos Flamin'' Hot Cool Ranch Flavored Tortilla Chips\, which pair perfectly with their parent tacos. And two other new menu items: the Cantina Crispy Chicken Taco (jalapeño buttermilk-marinated chicken\, rolled in tortilla chips\, topped with lettuce\, cheddar\, and tomatoes\, and wrapped in a soft taco shell) and the Cantina Crispy Chicken Tortada (a folded square take on the Crunchwrap Supreme\, without the tostada shell).','2022-08-19T13:06:28.981Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('3a5aa6a3-7d4b-43f8-8568-77240bc3e9f4','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16609144337056news.webp?alt=media&token=88ff5bad-02fa-45a1-b8dd-540d96a14bf3','Wendy''s: Hot Honey Chicken Biscuit and Hot Honey Chicken Sandwich','Wendy''s is launching two new innovations in its restaurant starting Feb. 8 to ensure customers spend all day with their hot honey... literally!\n\nThe Hot Honey Chicken Biscuit is the first new addition to Wendy''s breakfast menu since its 2020 launch. It''s comprised of a savory\, chicken fillet drizzled with Wendy''s new hot honey and served on a warm and fluffy buttermilk biscuit.\n\nAfter breakfast\, try the Hot Honey Chicken sandwich\, Wendy''s newest addition to its ''Made to Crave'' menu. It boasts a spicy chicken breast\, melted Pepper Jack cheese\, three strips of Applewood smoked bacon\, crispy pickle chips — all topped with decadent hot honey on a toasted premium bun.','2022-08-19T13:07:17.366Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('6a55a562-9807-4b64-b287-25e85c36a13a','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16609144740097news.webp?alt=media&token=a10373b8-1673-4188-afc9-94e592fef75e','Subway: The Vault','Just in time for Super Bowl LVI\, Subway is introducing The Vault\, an exclusive menu with all-new sandwiches created by fan-favorite athletes. The menu includes:\n\nRussell Wilson''s The Dangerwich: Pepperoni\, salami\, black forest ham\, provolone cheese\, and bacon on Italian Herbs & Cheese bread. Topped with lettuce\, tomatoes\, green peppers\, banana peppers\, and finished with yellow mustard and mayonnaise.\n\nMarshawn Lynch''s The Beef Mode: Choice Angus Roast Beef\, pepper jack cheese\, and hickory smoked bacon on Italian Herbs & Cheese bread. Topped with lettuce\, tomatoes\, black olives\, red onions\, and jalapeños\, and drizzled with yellow mustard and Baja Chipotle sauce.\n\nTrevor Lawrence''s The Sunshine Sub: Oven roasted turkey\, BelGioioso fresh mozzarella cheese\, avocado and tomatoes\, all on Hearty Multigrain bread.','2022-08-19T13:07:59.354Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('54cc946a-f80c-4d0d-bc00-50bfe5f930ec','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16609145375688news.webp?alt=media&token=f162ff15-6044-4bfc-a8c0-6aa497eee029','Red Lobster: Lobsterfest','Lobster lovers rejoice! Lobsterfest is back at Red Lobster with a variety of cravable lobster-centric dishes like the new Lobster Topped Stuffed Flounder which finds wild-caught flounder roasted with Red Lobster''s signature seafood stuffing and topped with Maine and langostino lobster in a creamy lobster beurre blanc. It''s served with choice of two sides\, like the new Bacon Mac & Cheese.\n\nThere''s also the new Lobster Punch—made with Captain Morgan rum and Malibu coconut rum with pineapple and berry juices.\n\nAnd the Date Night Feast for Two\, which features two butter-poached Maine lobster tails\, two 7 oz. sirloins\, two jumbo grilled shrimp skewers and a shareable Bacon Mac & Cheese. Plus\, a choice of one side for each guest.','2022-08-19T13:09:02.315Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('3a5ab2b0-2394-42a1-93ec-deeae5d270c0','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F16609145825359news.webp?alt=media&token=f03a0829-d4a8-419a-8f3b-2e8df9018717','Shake Shack: Buffalo Chicken Sandwich and Buffalo Spiced Cheese Fries','For those craving the spicy flavor of one\nof America''s favorite football Sunday snacks\, Shake Shack has you covered! The chain has put a spin on two Shack classics — the Chicken Shack and Crinkle Cut Fries —by introducing its new Buffalo Chicken Sandwich and Buffalo Spiced Cheese Fries. Both use Shake Shack''s propriety Buffalo Sauce\, which takes the classic topping but adds more pronounced vinegary notes and a touch of garlic.\n\nBuffalo Chicken Sandwich:\nCrispy\, hand-breaded\, expertly seasoned\, antibiotic-free chicken breast cooked sous vide for perfect texture\, covered in Buffalo Sauce and topped with ranch sauce\, served over pickles and shredded lettuce on a toasted potato bun. Pricing starts at $7.79.\n\nBuffalo Spiced Cheese Fries:\nCrispy crinkle cuts topped with cheese sauce and dusted with Buffalo seasoning\, served with ranch sauce. Pricing starts at $4.79.\n\nShake Shack recommends eating both with its ranch sauce\, which they say is a better alternative to blue cheese with its \"flavorful\, dairy-rich notes and cooling effects.\"','2022-08-19T13:09:46.792Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('34982628-1cca-4d68-9db2-c98da25ff4df','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F166091462343910news.webp?alt=media&token=f3b6709f-c1ab-4a77-a102-a4ec951f5f91','Subway: Baja Turkey Avocado\, Honey Mustard Rotisserie-Style Chicken','Subway has been steadily adding new crave-worthy subs and signature exclusives to its U.S. menu. The newest additions include:\n\nBaja Turkey Avocado: Oven-roasted turkey and smashed avocado on hearty multigrain bread\, topped with crisp veggies — lettuce spinach\, tomatoes\, cucumber\, green peppers and red onion — and a generous drizzle of Subway''s spicy Baja chipotle sauce.\n\nHoney Mustard Rotisserie-Style Chicken: Subway''s rotisserie-style chicken gets a refresh with a sweet and tangy honey mustard sauce. The sub comes with lettuce\, spinach\, tomatoes\, cucumber\, green pepper\, and red onion. All are served on the brand''s hearty multigrain bread\, toasted to perfection. .\n\nIn addition to the new options\, several of Subway''s most popular sandwiches are now back on the menu including the Subway Club (pictured)\, as well as their Roast Beef\, Turkey Cali Fresh\, Baja Steak & Jack\, and Baja Chicken & Bacon sandwiches.','2022-08-19T13:10:27.081Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('fa545925-2620-41ba-9f01-942a2a7a0cd7','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F166091467192311news.webp?alt=media&token=0d8a47f2-aa96-4c33-ad30-c60e39a2efd2','White Castle: Spicy Joe Slider and Sloppy Fries','White Castle rang in 2022 with two new items: the Spicy Joe Slider and Sloppy Fries — teaming up with \"What''s Luv\" rapper and self-professed slider lover Fat Joe for the launch. The new Spicy Joe Slider tops White Castle''s traditional Sloppy Joe Slider with a spicy slice of jalapeño cheese and jalapeño crisps. The Sloppy Fries\, meanwhile\, covers the brand''s signature crispy crinkle fries with melted cheese and a tangy Sloppy Joe sauce.\n\nThe new items will be on the menu through Feb. 19.\n\nFans can mix or match the Spicy Joe Slider and their classic Sloppy Joe Slider with the Smoky Joe Slider — a returning favorite\, featuring smoked cheddar cheese and crispy onions — in a \"Joe 6-Pack\" for $6.','2022-08-19T13:11:16.675Z');
-- insert into news (news_id, news_img, news_title, news_desc, created_at) values ('e214b165-b307-4197-8122-e2509e664aba','https://firebasestorage.googleapis.com/v0/b/eaturkish-ae0b4.appspot.com/o/news%2F166091471258112news.webp?alt=media&token=46a2849c-8726-4035-a3d7-6c7f523e3120','Red Lobster: 3 From the Sea','Red Lobster is giving fans a deal in the new year\, with their 3 from the Sea offering. Fans can get a soup or salad\, individual-sized starter\, and entrée for just $15.99!\n\nThe full 3 from the Sea line-up includes:\n\nSoup or Salad:\n\n· New England Clam Chowder Cup\n\n· Lobster Bisque Cup (+$1)\n\n· House Salad\n\n· Caesar Salad\n\nIndividual-Sized Starter:\n\n· Parrot Isle Jumbo Coconut Shrimp\n\n· Mozzarella Cheesesticks\n\n· Signature Jumbo Shrimp Cocktail\n\nEntrée:\n\n· Fish & Chips\n\n· Shrimp Linguini Alfredo\n\n· Atlantic Salmon (+$2)\n\n· Hand-Breaded Chicken Tenders\n\n· Baha Shrimp Bowl\n\n· Wagyu Bacon Cheeseburger\n\n· Cajun Chicken Linguini Alfredo','2022-08-19T13:12:00.379Z');
